services:
  User.SaveUserPutController:
    class: ../../api/controller/user/SaveUserPutController
    arguments: ['@Shared.CommandBus']

  User.UpdateUserPostController:
    class: ../../api/controller/user/UpdateUserPostController
    arguments: ['@User.UpdateUser']

  User.Find:
    class:  ../../modules/user/application/FindUser
    arguments: ['@User.Repository']

  User.Save:
    class: ../../modules/user/application/save/SaveUser
    arguments: ['@User.Repository', '@Shared.Helpers.Bcrypt']

  User.SaveCommandHandler:
    class: ../../modules/user/application/save/SaveUserCommandHandler
    arguments: ['@User.Save']
    tags:
      - { name: 'commandHandler' }

  User.UpdateUser:
    class: ../../modules/user/application/UpdateUser
    arguments: ['@User.Repository']

  User.Repository:
    class: ../../modules/user/infraestructure/InMemoryRepository/InMemoryUserRepository
    arguments: []