services:
  User.SaveUserPutController:
    class: ../../api/controller/user/SaveUserPutController
    arguments: ['@Shared.CommandBus']

  User.UpdateUserPostController:
    class: ../../api/controller/user/UpdateUserPostController
    arguments: ['@Shared.CommandBus']

  User.Find:
    class:  ../../modules/User/application/FindUser
    arguments: ['@User.Repository']

  User.Save:
    class: ../../modules/User/application/save/SaveUser
    arguments: ['@User.Repository', '@Shared.Helpers.Bcrypt']

  User.SaveCommandHandler:
    class: ../../modules/User/application/save/SaveUserCommandHandler
    arguments: ['@User.Save']
    tags:
      - { name: 'commandHandler' }

  User.UpdateUser:
    class: ../../modules/User/application/update/UpdateUser
    arguments: ['@User.Repository']

  User.UpdateUserCommandHandler:
    class: ../../modules/User/application/update/UpdateUserCommandHandler
    arguments: ['@User.UpdateUser']
    tags: 
      - { name: 'commandHandler' }

  User.Repository:
    class: ../../modules/User/infraestructure/type-orm-repository/TypeOrmUserRepository
    arguments: ['@Shared.TypeORM']