services:
  Shared.Config:
    class: ../../config/Config
    arguments: []
  
  Shared.CommandBus:
    class: ../../modules/Shared/infraestructure/cqrs/in-memory/InMemoryCommandBus
    arguments: ['@Shared.CommandBusInformation']

  Shared.CommandBusInformation:
    class: ../../modules/Shared/infraestructure/cqrs/in-memory/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.QueryBus:
    class: ../../modules/Shared/infraestructure/cqrs/in-memory/InMemoryQueryBus
    arguments: ['@Shared.QueryBusInformation']

  Shared.QueryBusInformation:
    class: ../../modules/Shared/infraestructure/cqrs/in-memory/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.TypeORM:
    class: ../../modules/Shared/infraestructure/type-orm/TypeORM
    arguments: ['@Shared.Config']

  Shared.Helpers.Bcrypt:
    class: ../../modules/Shared/domain/helpers/Bcrypt
    arguments: []

  Shared.Helpers.Jwt:
    class: ../../modules/Shared/domain/helpers/JWT
    arguments: ['@Shared.Config']