services:
  Shared.Config:
    class: ../../config/Config
    arguments: []
  
  Shared.CommandBus:
    class: ../../modules/shared/infraestructure/cqrs/InMemory/InMemoryCommandBus
    arguments: ['@Shared.CommandBusInformation']

  Shared.CommandBusInformation:
    class: ../../modules/shared/infraestructure/cqrs/InMemory/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.QueryBus:
    class: ../../modules/shared/infraestructure/cqrs/InMemory/InMemoryQueryBus
    arguments: ['@Shared.QueryBusInformation']

  Shared.QueryBusInformation:
    class: ../../modules/shared/infraestructure/cqrs/InMemory/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.TypeORM:
    class: ../../modules/shared/infraestructure/TypeORM/TypeORM
    arguments: ['@Shared.Config']

  Shared.Helpers.Bcrypt:
    class: ../../modules/shared/domain/helpers/Bcrypt
    arguments: []

  Shared.Helpers.Jwt:
    class: ../../modules/shared/domain/helpers/JWT
    arguments: ['@Shared.Config']